name: softgym
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - imageio
  - glob2
  - pybind11
  - click
  - matplotlib
  - joblib
  - Pillow
  - plotly
  - pip
# SoftAgent specific
  - pip:
      - torch
      - torchvision
      - dm-env
      - dm-tree
      - termcolor
      - git+https://github.com/1nadequacy/dmc2gym.git
      - scikit-image
      - kornia
      - pyquaternion
      - opencv-python
      - gym
      - gtimer
      - tensorboard
      - wandb
      - stable-baselines3[extra]==1.3.1a9
  - moviepy
  - imageio-ffmpeg
  - sk-video